branches:
  except:
    - /travisXXX/
skip_tags: true
shallow_clone: true

#install:
#  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
install:
  - cinst vcredist2013
  - cinst nmake

build_script:
  - cd win
  - make
